name: "Build mythical images for PR"
on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - source/**

jobs:
    build_images:
        name: "Build PR images"
        permissions:
            contents: read
            packages: write

        uses: ./.github/workflows/publish-and-deploy-images.yaml
        with:
            push_images: true
            version: ${{ github.head_ref }}
        secrets: inherit
