name: "Release image versions for mythical"
on:
    release:
        types: [published]

    workflow_dispatch:
        inputs:
            version:
                description: "The version to build and release"
                required: true

jobs:
    build_images:
        name: "Build versioned images"
        permissions:
            contents: read
            packages: write

        uses: ./.github/workflows/publish-and-deploy-images.yaml
        with:
            push_images: true
            version: ${{ github.event.inputs.version || github.event.release.tag_name }}
        secrets: inherit
